### ISSUE TITLE
Publish API to Heroku

### ISSUE THREAD

**Issue by wayne-o** [wayne-o/sonatribe-api#1]
http://stackoverflow.com/questions/16205028/deploying-a-sails-js-app-to-heroku

**Comment by chrismou** [comment]
Took a while, but I think we're cooking on gas: https://sonatribe-api.herokuapp.com

Create a heroku account tomorrow and I'll add you as a collaborator so you can get at the instance. I've got papertrail running so there's a ton of logs to sift through if you need them
